port: ":3000"

auth:
  signing_key: "afLjrgTjlXV1Y5rSzoxtlnp1TOFF0Njk"
  token_ttl: 86400
    
database:
    host: "127.0.0.1"
    port: "5432"
    username: "postgres"
    password: "Esp0rt"
    name: "esport"